### ISSUE TITLE
"Solving obligations automatically..." does not complete

### ISSUE THREAD

**Issue by ANogin** [mattam82/Coq-Equations#116] opened 2018-06-12 23:21 UTC
With the latest v8.8, the following code
```
From Coq.Lists Require Import List.
From Equations Require Import Equations.

Inductive foo :=
| Sum : list foo -> foo.

Equations (struct t) do_foo1 (t: foo) : nat := {
  do_foo1 (Sum u) :=
        do_foo1_list2 u }

  where (struct ts)
    do_foo1_list (ts:list foo) : nat := {
    do_foo1_list nil := 0;
    do_foo1_list (cons t ts) := (do_foo1_list ts)}

  where (struct fs)
    do_foo1_list2 (fs : list foo) : nat := {
    do_foo1_list2 _ := 0}

  where (struct t) do_foo2 (t : foo) : nat := {
  do_foo2 _ := 0 }

  where (struct ts)
    do_foo2_list (ts:list foo) : nat := {
    do_foo2_list nil := 0;
    do_foo2_list (cons t ts) <= (do_foo2_list ts) => {
      do_foo2_list (cons t _) _ := (do_foo1 t) + (do_foo2 t)}}.
```
gets stuck after
```
do_foo1_functional has type-checked.
do_foo1_functional is defined
do_foo1_list_functional has type-checked.
do_foo1_list_functional is defined
do_foo1_list2_functional has type-checked.
do_foo1_list2_functional is defined
do_foo2_functional has type-checked.
do_foo2_functional is defined
do_foo2_list_functional has type-checked, generating 1 obligation
Solving obligations automatically...
do_foo2_list_obligation_1 is defined
No more obligations remaining
do_foo2_list_functional is defined
do_foo1 is defined
do_foo1_list is defined
do_foo1_list2 is defined
do_foo2 is defined
do_foo2_list is defined
do_foo1_equation_1 has type-checked, generating 1 obligation
Solving obligations automatically...
```
P.S. The specific example is not truly mutually recursive, but it is minimized from a one that is; and there does not seem to be any difference in behavior. At the same time, removing things further seem to cause it to fail in a different way - such as getting issue #79 instead.

**Comment by mattam82** [comment] 2018-06-13 10:04
Hmm, it's tricky. The way I encode nested recursive definitions gives rise to exponentially large terms (you can look at do_foo1's definition if you set the (noeqns) option) and I'm not sure a more compact representation can be found.

**Comment by mattam82** [comment] 2018-06-13 11:02
Actually only the first equation results in an explosion because of an agressive unfolding. Maybe that can be fixed.

**Comment by mattam82** [comment] 2018-06-13 17:19
Indeed I found a fix. Same as in #74, the automated proof of the induction principle fails. To fix this we will have to repeat nested fixpoint proofs at each occurrence of the nested fixpoint.

**Comment by mattam82** [comment] 2019-01-25 14:33
This is a duplicate of #74 now

**Closed by mattam82** 2019-01-25 14:33 UTC
