### ISSUE TITLE
Anomaly File "src/sigma_types.ml"

### ISSUE THREAD

**Issue by TDiazT** [mattam82/Coq-Equations#194] opened 2019-03-22 22:19 UTC
I used `funelim` in the following context : 

```
 Lemma β__φ_cat q qs qs' :
    β__φ q (qs ++ qs') = (β__φ q qs) ++ (β__φ q qs').
  Proof.
    funelim β__φ.
```

and got the following error message:
```
Error: Anomaly "File "src/sigma_types.ml", line 118, characters 10-16: Assertion failed."
Please report at http://coq.inria.fr/bugs/.
```

Where the function basically traverses a list and extract something from each element. The code is the  following (simplified) : 
`β__φ : Query -> seq Query -> seq Query`

```
Equations β__φ (flt : @Query Name Vals) (queries : seq (@Query Name Vals)) : seq (@Query Name Vals) :=
    {
      β__φ _ [::] := [::];
      β__φ flt (cons hd tl) := (β__subqueryextract flt hd) ++ (β__φ flt tl)
      where
      β__subqueryextract : @Query Name Vals -> @Query Name Vals -> seq (@Query Name Vals) :=
        {
          β__subqueryextract (NestedField f α β) (NestedField f' α' χ)
            with f == f', α == α' :=
            {
             ...
            };
          
          β__subqueryextract (NestedLabeledField l f α β) (NestedLabeledField l' f' α' χ)
            with [&& l == l', (f == f') & (α == α')] :=
            {
             ...
            };
          
          β__subqueryextract (InlineFragment t β) (InlineFragment t' χ)
            with (t == t') :=
            {
            ...
            };
          
          β__subqueryextract _ _ := [::]
        }
    }.
``` 

I know that's not how you are supposed to use `funelim` but I was wondering what would come out of it 👀.

**Comment by TDiazT** [comment] 2019-04-04 23:34
A simpler example, but I get the same error:

```
Variables (T1 T2 : Type).

Equations indexed_map_In s (f : forall (i : nat) (x : T1), In x s -> T2) (index : nat) : seq T2 :=
      { 
        indexed_map_In [::] _ _ := [::];
        indexed_map_In (hd :: tl) f i := (f i hd _) :: (indexed_map_In tl (fun i x H => f i x _) i.+1)
      }.

 Lemma error_lem (s : seq T1) (v : T2) :
    indexed_map_In s (fun i n _ => v) 0 <> [::].
  Proof.
    funelim (indexed_map_In _ _ ).
  

```

**Comment by mattam82** [comment] 2021-05-04 18:24
Duplicate of #372

**Closed by mattam82** 2021-05-04 18:24 UTC
