### ISSUE TITLE
Illegal application

### ISSUE THREAD

**Issue by ANogin** [mattam82/Coq-Equations#105] opened 2018-06-06 23:12 UTC
With the latest v8.8, the following slight modification on the definition from issue #104 
```From Coq.Lists Require Import List.
From Equations Require Import Equations.

(* This type is from VST: 
 * https://github.com/PrincetonUniversity/VST/blob/v2.1/floyd/compact_prod_sum.v#L13 *)
Fixpoint compact_sum (T: list Type): Type :=
  match T with
  | nil => unit
  | t :: nil => t
  | t :: T0 => (t + compact_sum T0)%type
end.

(* The rest is a nonsensical, just to give a reproducible example *)
Inductive foo :=
| Sum : (foo * list foo) -> foo.

Equations foo_type (t : foo) : Type :=
  foo_type (Sum u) :=
    (foo_type (fst u))
    * (compact_sum (List.map foo_type (snd u))).

Equations (struct f) do_foo (f : foo) : forall (val : foo_type f), nat := {
  do_foo (Sum (pair s1 s2)) := fun val =>
    (do_foo s1 (fst val)) + (do_sum s1 (fst val) s2 (snd val)) }

  where (struct fs)
    do_sum (f : foo) (otherval : foo_type f) (fs : list foo) :
      forall val : compact_sum (List.map foo_type fs), nat := {
    do_sum _ _ nil := fun val => 0;
    do_sum f otherval (cons hd tl) <= (fun val => do_sum f otherval tl val) => {
      do_sum _ _ (cons var nil) _ :=
        fun val => do_foo var val;
      do_sum _ _ (cons hd tl) do_foo_tl := fun val =>
        match val with
        | inl vh => do_foo hd vh
        | inr vstl => do_foo_tl vstl
        end }}.
```
results in
```
Illegal application: 
The term "@fst" of type "forall A B : Type, A * B -> A"
cannot be applied to the terms
 "(fix foo_type (t : foo) : Type :=
     match t with
     | Sum p => (foo_type (fst p) * compact_sum (map foo_type (snd p)))%type
     end) (fst (f, l))" : "Type"
 "compact_sum
    (map
       (fix foo_type (t : foo) : Type :=
          match t with
          | Sum p => (foo_type (fst p) * compact_sum (map foo_type (snd p)))%type
          end) (snd (f, l)))" : "Type"
 "Hind" : "foo_type (Sum (f, l)) -> do_foo_ind f (do_foo f)"
The 3rd term has type "foo_type (Sum (f, l)) -> do_foo_ind f (do_foo f)" which should be coercible to
 "((fix foo_type (t : foo) : Type :=
      match t with
      | Sum p => foo_type (fst p) * compact_sum (map foo_type (snd p))
      end) (fst (f, l)) *
   compact_sum
     (map
        (fix foo_type (t : foo) : Type :=
           match t with
           | Sum p => foo_type (fst p) * compact_sum (map foo_type (snd p))
           end) (snd (f, l))))%type".
```

I have not tried too hard to further minimize this. Not 100% sure whether this is my fault, or a bug.

**Comment by mattam82** [comment] 2018-06-07 17:09
Indeed it was a duplicate of #85 whose fix is incoming. Good thing is all this drove me to simplify the code and avoid potentially other de Bruijn bugs like these.

**Closed by mattam82** 2018-06-07 17:09 UTC
